MIDI_ENABLE = yes

# Root overrides
BOOTMAGIC_ENABLE = yes 
#MOUSEKEY_ENABLE = yes  
MOUSEKEY_ENABLE = no
CONSOLE_ENABLE = no
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = WS2812
LTO_ENABLE = yes

# more squeezin
COMMAND_ENABLE = no
EXTRAKEY_ENABLE = yes
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no

# Vial settings
VIA_ENABLE = yes
VIAL_ENABLE = yes
ENCODER_MAP_ENABLE = yes
VIALRGB_ENABLE = yes

# Reduce firmware size
QMK_SETTINGS = no
TAP_DANCE_ENABLE = no
COMBO_ENABLE = no
KEY_OVERRIDE_ENABLE = no

SRC += oled.c
